### ISSUE TITLE
请教：函数的默认参数是列表时我不理解

### ISSUE THREAD

**Issue by LaoLiulaoliu** [hit9/PyZh#16]
9.3 注意函数的默认参数
def foo(x=[]): x.append(1); print(x)
foo(); foo()
得到：
[1]
[1, 1]

第一次调用foo() 得到x =[] ，然后x = [1]，x指向列表[1]内存中的地址。
但是第二次调用foo() , x = [] 不是把x指向另一个列表[] 的地址吗？

**Comment by skyline75489** [comment]
参考 Python 官方 Tutorial 中的内容

> **Important warning**: The default value is evaluated only once. This makes a difference when the default is a mutable object such as a list, dictionary, or instances of most classes. For example, the following function accumulates the arguments passed to it on subsequent calls:

即默认参数只进行一次计算，导致第二次传入时仍然是同一个List.

**Comment by LaoLiulaoliu** [comment]
这下明白了，谢谢
